#include "LivingPartyTraining.h"
#include "../realm/TrainingSpellSet.h"
#include "LivingPartyService.h"
#include "LivingActivityRequests.h"
#include <cassert>
using namespace LivingActivity;
int main() {
    assert(SameTrainingSpellSet("4187,24545,2649","2649,4187,24545"));
    assert(!SameTrainingSpellSet("4187,24545","2649,4187,24545"));
    assert(!SameTrainingSpellSet("4187,24545,2649,4187","2649,4187,24545"));
    for(const auto* invalid:{"","4187,","4187,,24545","-4187","4294967296","4187x"})
        assert(!SameTrainingSpellSet(invalid,"4187"));
    PartyTrainingJob job{123,0,{100,200}},decoded;
    const auto encoded=EncodePartyTrainingJob(job);
    assert(DecodePartyTrainingJob(encoded,decoded));
    for(const auto bad:{"{}","[]","", "null"})assert(!DecodePartyTrainingJob(bad,decoded));
    assert(!DecodePartyTrainingJob(encoded+"{}",decoded));
    auto changed=job;changed.lessons={100,100};assert(!ValidPartyTrainingJob(changed));
    changed=job;changed.next=3;assert(!ValidPartyTrainingJob(changed));
    changed=job;changed.lessons.clear();assert(!ValidPartyTrainingJob(changed));
    changed=job;changed.trainer=0;assert(!ValidPartyTrainingJob(changed));
    Task task;task.id=task.root="11111111-1111-4111-8111-111111111111";
    task.source="party_training";task.sourceKey="training:7:1";task.actor=7;task.kind=Kind::PartyErrand;
    task.mode=Mode::Active;task.accepted=true;task.phase=Phase::Preparing;task.revision=4;
    task.createdAtMs=task.updatedAtMs=1000;task.context.actor=7;
    task.context.actorGeneration=task.context.mapGeneration=task.context.policyRevision=1;
    task.context.boot="22222222-2222-4222-8222-222222222222";
    task.checkpoint.step="party_training_prepare";task.checkpoint.data=encoded;std::string why;
    assert(ValidatePartyTrainingTask(task,why));
    auto traveling=task;traveling.phase=Phase::Traveling;traveling.checkpoint.step=ServiceStep(ServiceDestination::ClassTrainer);
    assert(ValidatePartyTrainingTask(traveling,why));
    ServiceDestination service;assert(ParseServiceStep(traveling.checkpoint.step,service) && service==ServiceDestination::ClassTrainer);
    auto wrongService=traveling;wrongService.checkpoint.step=ServiceStep(ServiceDestination::Vendor);
    assert(!ValidatePartyTrainingTask(wrongService,why));
    Task arrived;ServiceTravelResult route;route.arrived=true;
    assert(CheckpointServiceTravel(traveling,route,2000,"party_training_prepare",arrived));
    assert(arrived.phase==Phase::Preparing && arrived.checkpoint.data==encoded && arrived.checkpoint.step=="party_training_prepare");
    assert(ValidatePartyTrainingTask(arrived,why));
    auto bad=task;bad.phase=Phase::Completed;assert(!ValidatePartyTrainingTask(bad,why));
    bad=task;bad.kind=Kind::Profession;assert(!ValidatePartyTrainingTask(bad,why));
    TaskRequest request;request.task=task;++request.task.revision;request.expectedRevision=task.revision;request.receipt=task.context.boot;
    assert(ValidateTaskRequest(request,&task,task.context,why)==AdmissionCode::Pending);
    changed=job;changed.next=1;request.task.checkpoint.data=EncodePartyTrainingJob(changed);
    assert(ValidateTaskRequest(request,&task,task.context,why)==AdmissionCode::InvalidRequest);
    TrainingLessonQuote q;q.actor=7;q.trainer=321;q.lesson=q.teachingSpell=100;q.playerSpells={100};q.money=50;
    TrainingLessonQuote copy;assert(DecodeDirectTrainingQuote(EncodeDirectTrainingQuote(q),copy));
    assert(SameTrainingLessonQuote(q,copy) && PartyTrainingQuoteMatches(task,q));
    auto invalid=q;invalid.cost=1;assert(!DirectFreeTrainingQuote(invalid));
    invalid=q;invalid.cast=true;assert(!DirectFreeTrainingQuote(invalid));
    invalid=q;invalid.playerSpells={100,200};assert(!DirectFreeTrainingQuote(invalid));
    invalid=q;invalid.actor=8;assert(!PartyTrainingQuoteMatches(task,invalid));
    OperationResult proof;proof.id=task.context.boot;proof.task=task.id;proof.taskRevision=4;
    proof.kind="party_training_learn";proof.state=OperationState::Verified;
    proof.nativeReference="trainer_lesson:100";proof.evidence="native_training_exact_spellbook_and_unchanged_money";
    auto after=task;++after.revision;after.phase=Phase::Verifying;after.checkpoint.step="party_training_learn";
    bad=after;auto failed=proof;failed.state=OperationState::Rejected;
    assert(!AcknowledgePartyTraining(bad,q,failed));
    assert(AcknowledgePartyTraining(after,q,proof));
    assert(after.phase==Phase::Verifying && DecodePartyTrainingJob(after.checkpoint.data,decoded) && decoded.next==1);
    assert(!AcknowledgePartyTraining(after,q,proof));
    auto journal=OperationOutcomeWrite(after,4,proof,task.id,"{}");assert(!journal.statements.empty());
    q.lesson=q.teachingSpell=200;q.playerSpells={200};proof.taskRevision=5;proof.nativeReference="trainer_lesson:200";
    ++after.revision;assert(AcknowledgePartyTraining(after,q,proof));
    assert(after.phase==Phase::Completed);
    journal=OperationOutcomeWrite(after,5,proof,task.id,"{}");assert(!journal.statements.empty());
    failed=proof;failed.nativeReference="trainer_lesson:100";bool threw=false;
    try{OperationOutcomeWrite(after,5,failed,task.id,"{}");}catch(...){threw=true;}assert(threw);
    PartyServiceBinding binding;binding.root=task.id;binding.actor=7;binding.human=8;
    binding.session="group:3:4";binding.sessionRevision=2;binding.acceptedRevision=4;
    binding.service=PartyServiceBinding::Service::Training;
    PartyServiceWindow window{7,8,"group:3:4",2,true};
    assert(PartyServiceMatches(binding,task,window));window.authorized=false;
    assert(!PartyServiceMatches(binding,task,window));
    assert(PartyServiceEffects(Mask(Effect::Spell)|Mask(Effect::Social),binding.service));
    assert(!PartyServiceEffects(Mask(Effect::Money),binding.service));
    assert(!PartyServiceEffects(Mask(Effect::Inventory),binding.service));
    assert(PartyServiceOperation(binding,"party_training_learn",{}));
    assert(!PartyServiceOperation(binding,"profession_craft",{}));
    assert(PartyServiceReceipt(binding,after,"party_training_learn",{},proof.id));
    assert(!PartyServiceReceipt(binding,after,"party_training_learn",{},proof.id));

    // Direct journal fingerprints remain byte-for-byte compatible.
    q.lesson=q.teachingSpell=100;q.playerSpells={100};
    assert(EncodePartyTrainingQuote(q)==EncodeDirectTrainingQuote(q));
    assert(DecodePartyTrainingQuote(EncodeDirectTrainingQuote(q),copy) && SameTrainingLessonQuote(q,copy));
    q.cast=true;q.lesson=q.teachingSpell=10321;q.playerSpells={20271,21084};
    assert(FreePlayerTrainingCastQuote(q) && !DirectFreeTrainingQuote(q));
    assert(DecodePartyTrainingQuote(EncodePartyTrainingQuote(q),copy) && SameTrainingLessonQuote(q,copy));
    assert(!DecodeDirectTrainingQuote(EncodePartyTrainingQuote(q),copy));
    assert(!DecodePartyTrainingQuote(EncodePartyTrainingQuote(q)+"{}",copy));
    invalid=q;invalid.playerSpells={21084,20271};assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.petSpells={7};invalid.pet=9;assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.cost=1;assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.playerSpells={10321};assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.playerSpells={20271,20271};assert(!FreePlayerTrainingCastQuote(invalid));
    assert(!DecodePartyTrainingQuote(EncodePartyTrainingQuote(invalid),copy));
    TrainingCastResult cast;cast.before.actor=q.actor;cast.before.money=q.money;
    cast.before.playerSpells={17,21084}; // A previously known second target is valid.
    cast.after=cast.before;cast.after.playerSpells.insert(20271);
    cast.started=cast.effect=cast.finished=cast.succeeded=true;
    assert(VerifyTrainingCast(q,cast,why)==OperationState::Verified && why==PartyTrainingEvidence(q));
    auto broken=cast;broken.after.playerSpells.erase(20271);
    assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.after.playerSpells.insert(99);assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.after.playerSpells.erase(17);assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;--broken.after.money;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;++broken.after.actor;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;++broken.after.pet;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.finished=false;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.uncertain=true;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.effect=false;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.succeeded=false;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.effect=broken.succeeded=false;broken.after=broken.before;
    assert(VerifyTrainingCast(q,broken,why)==OperationState::Rejected);
    broken=cast;broken.before.playerSpells.insert(20271);assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    job={123,0,{10321}};task.checkpoint.data=EncodePartyTrainingJob(job);
    after=task;++after.revision;after.phase=Phase::Verifying;after.checkpoint.step="party_training_learn";
    proof.taskRevision=task.revision;proof.nativeReference="trainer_lesson:10321";
    proof.evidence="native_training_exact_spellbook_and_unchanged_money";
    assert(!AcknowledgePartyTraining(after,q,proof)); // Direct evidence cannot acknowledge a cast.
    proof.evidence=PartyTrainingEvidence(q);assert(AcknowledgePartyTraining(after,q,proof));
    assert(after.phase==Phase::Completed);
    assert(!OperationOutcomeWrite(after,task.revision,proof,task.id,"{}").statements.empty());
    q.skill={762,{}, {75,75,1}};
    assert(FreePlayerTrainingCastQuote(q));
    assert(DecodePartyTrainingQuote(EncodePartyTrainingQuote(q),copy) && SameTrainingLessonQuote(q,copy));
    assert(EncodePartyTrainingQuote(q).find("training_cast_v2")!=std::string::npos);
    cast.skillsBefore={{164,{25,75,1}}};cast.skillsAfter=cast.skillsBefore;cast.skillsAfter[762]={75,75,1};
    assert(VerifyTrainingCast(q,cast,why)==OperationState::Verified && why==PartyTrainingEvidence(q));
    broken=cast;broken.skillsAfter.erase(762);assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.skillsAfter[762].maximum=150;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.skillsAfter[762].step=2;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.skillsAfter[164].value=26;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    broken=cast;broken.skillsBefore[762]={1,75,1};assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    invalid=q;invalid.skill.after={74,75,0};assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.skill.before={150,150,2};assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.skill.id=0;assert(!FreePlayerTrainingCastQuote(invalid));
    invalid=q;invalid.cast=false;assert(!DirectFreeTrainingQuote(invalid));
    q.skill={};broken=cast;assert(VerifyTrainingCast(q,broken,why)==OperationState::Reconciling);
    std::set<uint32_t> persisted;
    assert(TrainingPersistenceTargets({33388,34769},{33388},{{34769,33388}},persisted));
    assert(persisted==std::set<uint32_t>{34769});
    assert(!TrainingPersistenceTargets({33388,34769},{33388},{},persisted));
    assert(!TrainingPersistenceTargets({33388,34769},{33388,34769},{{34769,33388},{33388,34769}},persisted));
    assert(!TrainingPersistenceTargets({33388},{33388},{{34769,33388}},persisted));
    assert(!TrainingPersistenceTargets({34769},{33388},{},persisted));
    assert(TrainingPersistenceTargets({1,2,3},{2,3},{{1,2},{2,3}},persisted) && persisted==std::set<uint32_t>{1});
    assert(TrainingPersistenceTargets({20271,21084},{},{},persisted) && persisted.size()==2);
    assert(TrainingPersistenceTargets({},{},{},persisted) && persisted.empty());
    q={};q.actor=7;q.trainer=123;q.lesson=q.teachingSpell=3101;q.money=150;q.playerSpells={3101};
    q.skill={171,{50,75,1},{50,150,2}};
    assert(DirectSkillTrainingQuote(q) && ManagedTrainingQuote(q) && !DirectFreeTrainingQuote(q) && !FreePlayerTrainingCastQuote(q));
    assert(DecodePartyTrainingQuote(EncodePartyTrainingQuote(q),copy) && SameTrainingLessonQuote(q,copy));
    assert(EncodePartyTrainingQuote(q).find("training_direct_skill_v1")!=std::string::npos);
    TrainingLessonState tierBefore;tierBefore.actor=7;tierBefore.money=150;tierBefore.playerSpells={2259,2330};
    auto tierAfter=tierBefore;tierAfter.playerSpells.insert(3101);
    std::map<uint16_t,TrainingSkillState> skillsBefore{{171,{50,75,1}},{164,{10,75,1}}},skillsAfter=skillsBefore;
    skillsAfter[171]={50,150,2};
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierAfter,skillsBefore,skillsAfter,why)==OperationState::Verified);
    assert(why=="native_training_exact_direct_skill_and_spellbook");
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierBefore,skillsBefore,skillsBefore,why)==OperationState::Rejected);
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierAfter,skillsBefore,skillsBefore,why)==OperationState::Reconciling);
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierBefore,skillsBefore,skillsAfter,why)==OperationState::Reconciling);
    auto changedSkills=skillsAfter;changedSkills[164].value++;
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierAfter,skillsBefore,changedSkills,why)==OperationState::Reconciling);
    changedSkills=skillsAfter;changedSkills[171].value++;
    assert(VerifyDirectTrainingSkill(q,tierBefore,tierAfter,skillsBefore,changedSkills,why)==OperationState::Reconciling);
    auto wrongTier=tierAfter;wrongTier.money--;
    assert(VerifyDirectTrainingSkill(q,tierBefore,wrongTier,skillsBefore,skillsAfter,why)==OperationState::Reconciling);
    wrongTier=tierAfter;wrongTier.playerSpells.insert(99);
    assert(VerifyDirectTrainingSkill(q,tierBefore,wrongTier,skillsBefore,skillsAfter,why)==OperationState::Reconciling);
    invalid=q;invalid.skill.before={};assert(!DirectSkillTrainingQuote(invalid));
    invalid=q;invalid.skill.after.value++;assert(!DirectSkillTrainingQuote(invalid));
    invalid=q;invalid.skill.after.maximum=75;assert(!DirectSkillTrainingQuote(invalid));
    invalid=q;invalid.skill.after.step=1;assert(!DirectSkillTrainingQuote(invalid));
    invalid=q;invalid.cost=1;assert(!DirectSkillTrainingQuote(invalid));
    invalid=q;invalid.petSpells={7};invalid.pet=9;assert(!DirectSkillTrainingQuote(invalid));
    job={123,0,{3101}};task.actor=q.actor;task.checkpoint.data=EncodePartyTrainingJob(job);
    after=task;++after.revision;after.phase=Phase::Verifying;after.checkpoint.step="party_training_learn";
    proof.nativeReference="trainer_lesson:3101";proof.evidence="native_training_exact_spellbook_and_unchanged_money";
    assert(!AcknowledgePartyTraining(after,q,proof));
    proof.evidence=PartyTrainingEvidence(q);assert(AcknowledgePartyTraining(after,q,proof) && after.phase==Phase::Completed);
    q={};q.actor=7;q.trainer=321;q.lesson=q.teachingSpell=4195;q.money=50;q.cast=true;
    q.pet=999;q.petNumber=12;q.petEntry=705;q.petLevel=12;q.petPoints=45;q.petPointCost=5;q.petSpells={4187};
    assert(FreePetTrainingQuote(q) && ManagedTrainingQuote(q));
    assert(DecodePartyTrainingQuote(EncodePartyTrainingQuote(q),copy) && SameTrainingLessonQuote(q,copy));
    assert(!DecodePartyTrainingQuote(EncodePartyTrainingQuote(q)+" ",copy));
    TrainingLessonState petBefore;petBefore.actor=7;petBefore.money=50;petBefore.pet=999;
    petBefore.playerSpells={75,883};petBefore.petSpells={2649,17253};
    auto petAfter=petBefore;petAfter.petSpells.insert(4187);
    assert(VerifyPetTraining(q,petBefore,petAfter,12,12,45,40,why)==OperationState::Verified);
    assert(why=="native_training_exact_pet_spellbook_and_points");
    assert(VerifyPetTraining(q,petBefore,petBefore,12,12,45,45,why)==OperationState::Rejected);
    assert(VerifyPetTraining(q,petBefore,petBefore,12,12,45,40,why)==OperationState::Reconciling);
    assert(VerifyPetTraining(q,petBefore,petAfter,12,12,45,45,why)==OperationState::Reconciling);
    assert(VerifyPetTraining(q,petBefore,petAfter,12,13,45,40,why)==OperationState::Reconciling);
    auto wrongPet=petAfter;wrongPet.pet=1000;
    assert(VerifyPetTraining(q,petBefore,wrongPet,12,12,45,40,why)==OperationState::Reconciling);
    wrongPet=petAfter;wrongPet.playerSpells.insert(4187);
    assert(VerifyPetTraining(q,petBefore,wrongPet,12,12,45,40,why)==OperationState::Reconciling);
    wrongPet=petAfter;wrongPet.petSpells.erase(2649);
    assert(VerifyPetTraining(q,petBefore,wrongPet,12,12,45,40,why)==OperationState::Reconciling);
    wrongPet=petAfter;wrongPet.money--;
    assert(VerifyPetTraining(q,petBefore,wrongPet,12,12,45,40,why)==OperationState::Reconciling);
    q.petReplacedSpell=2649;petAfter.petSpells.erase(2649);
    assert(VerifyPetTraining(q,petBefore,petAfter,12,12,45,40,why)==OperationState::Verified);
    invalid=q;invalid.petPointCost=46;assert(!FreePetTrainingQuote(invalid));
    invalid=q;invalid.petNumber=0;assert(!FreePetTrainingQuote(invalid));
    invalid=q;invalid.petSpells.push_back(9999);assert(!FreePetTrainingQuote(invalid));
    invalid=q;invalid.playerSpells={4195};assert(!FreePetTrainingQuote(invalid));
    invalid=q;invalid.petPoints=-1;assert(!FreePetTrainingQuote(invalid));
    invalid=q;invalid.petReplacedSpell=4187;assert(!FreePetTrainingQuote(invalid));
    job={123,0,{4195}};task.actor=q.actor;task.checkpoint.data=EncodePartyTrainingJob(job);
    after=task;++after.revision;after.phase=Phase::Verifying;after.checkpoint.step="party_training_learn";
    proof.nativeReference="trainer_lesson:4195";proof.evidence="native_training_exact_spellbook_and_unchanged_money";
    assert(!AcknowledgePartyTraining(after,q,proof));proof.evidence=PartyTrainingEvidence(q);
    assert(AcknowledgePartyTraining(after,q,proof) && after.phase==Phase::Completed);
}
